/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalaryRouteImport } from './routes/_app/salary'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPartTimeAnalyticsRouteImport } from './routes/_app/part-time-analytics'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAdvanceRouteImport } from './routes/_app/advance'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees.index'
import { Route as AppEmployeesPartTimeRouteImport } from './routes/_app/employees.part-time'
import { Route as AppEmployeesFullTimeRouteImport } from './routes/_app/employees.full-time'
import { Route as AppEmployeesIdRouteImport } from './routes/_app/employees.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPartTimeAnalyticsRoute = AppPartTimeAnalyticsRouteImport.update({
  id: '/part-time-analytics',
  path: '/part-time-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvanceRoute = AppAdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesPartTimeRoute = AppEmployeesPartTimeRouteImport.update({
  id: '/employees/part-time',
  path: '/employees/part-time',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesFullTimeRoute = AppEmployeesFullTimeRouteImport.update({
  id: '/employees/full-time',
  path: '/employees/full-time',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/advance': typeof AppAdvanceRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/part-time-analytics': typeof AppPartTimeAnalyticsRoute
  '/reports': typeof AppReportsRoute
  '/salary': typeof AppSalaryRoute
  '/settings': typeof AppSettingsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/full-time': typeof AppEmployeesFullTimeRoute
  '/employees/part-time': typeof AppEmployeesPartTimeRoute
  '/employees/': typeof AppEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/advance': typeof AppAdvanceRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/part-time-analytics': typeof AppPartTimeAnalyticsRoute
  '/reports': typeof AppReportsRoute
  '/salary': typeof AppSalaryRoute
  '/settings': typeof AppSettingsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/full-time': typeof AppEmployeesFullTimeRoute
  '/employees/part-time': typeof AppEmployeesPartTimeRoute
  '/employees': typeof AppEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/advance': typeof AppAdvanceRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/part-time-analytics': typeof AppPartTimeAnalyticsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/salary': typeof AppSalaryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/employees/full-time': typeof AppEmployeesFullTimeRoute
  '/_app/employees/part-time': typeof AppEmployeesPartTimeRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/advance'
    | '/attendance'
    | '/dashboard'
    | '/part-time-analytics'
    | '/reports'
    | '/salary'
    | '/settings'
    | '/employees/$id'
    | '/employees/full-time'
    | '/employees/part-time'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/advance'
    | '/attendance'
    | '/dashboard'
    | '/part-time-analytics'
    | '/reports'
    | '/salary'
    | '/settings'
    | '/employees/$id'
    | '/employees/full-time'
    | '/employees/part-time'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/advance'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/part-time-analytics'
    | '/_app/reports'
    | '/_app/salary'
    | '/_app/settings'
    | '/_app/employees/$id'
    | '/_app/employees/full-time'
    | '/_app/employees/part-time'
    | '/_app/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary': {
      id: '/_app/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/part-time-analytics': {
      id: '/_app/part-time-analytics'
      path: '/part-time-analytics'
      fullPath: '/part-time-analytics'
      preLoaderRoute: typeof AppPartTimeAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advance': {
      id: '/_app/advance'
      path: '/advance'
      fullPath: '/advance'
      preLoaderRoute: typeof AppAdvanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/part-time': {
      id: '/_app/employees/part-time'
      path: '/employees/part-time'
      fullPath: '/employees/part-time'
      preLoaderRoute: typeof AppEmployeesPartTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/full-time': {
      id: '/_app/employees/full-time'
      path: '/employees/full-time'
      fullPath: '/employees/full-time'
      preLoaderRoute: typeof AppEmployeesFullTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvanceRoute: typeof AppAdvanceRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPartTimeAnalyticsRoute: typeof AppPartTimeAnalyticsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppEmployeesFullTimeRoute: typeof AppEmployeesFullTimeRoute
  AppEmployeesPartTimeRoute: typeof AppEmployeesPartTimeRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvanceRoute: AppAdvanceRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPartTimeAnalyticsRoute: AppPartTimeAnalyticsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppEmployeesFullTimeRoute: AppEmployeesFullTimeRoute,
  AppEmployeesPartTimeRoute: AppEmployeesPartTimeRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
